local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq(data) m=string.sub(data, 0, 55) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


function gtZKSLKIUkfGcTPIIeDRykWkZeDlepbxzMMyncRnKRJzHGuZsjODAzhWHVEzcZPtvKkZYDMzWzFOKedrFYa(c)
tab={}
for i = 1,#c do
x=string.len(c[i]) 
y=string.char(x)
table.insert(tab,y)
end
x=table.concat(tab)
return x
end 



for __, v in pairs(game.CoreGui.RobloxGui.PerformanceStats:GetChildren()) do
    if v.Name == gtZKSLKIUkfGcTPIIeDRykWkZeDlepbxzMMyncRnKRJzHGuZsjODAzhWHVEzcZPtvKkZYDMzWzFOKedrFYa({VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('kuITcYZfKtvgCGagLjrStwgeOIQQpUvglPTORfGQBWcfTCbnYRIvtByKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('EMZwwLqeShZsIcHjAJlpeVsSllbDvwDXmkOOCoadyGgxrOAWINrJFyRKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('QHkqLYZcsqkgqEZHYQNVkUBljlxvdmpDoQZUJipreBnMsETcGAdTiWNKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('ZtgjyCDraHtRbhZNWqsCKpHyXheEIqFNIiHtsdrMraqhMpGVSwyplTtKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq'),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('fGFzPUdtPtJhkTJaVclAfXRBlotaCXHaQhVUehnOsLvwxOYoMgbJDLBKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq'),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('hCyIprrGYxuGROXlTNhEpIIPygaLabjnBWUheWBYtMDfEqzVZuToCpOKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('RLOZxCAHLLyZnbyTHaGwmRfRomJjuzELRgzlskqANjjsjKiOhFfiDUzKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('BYKWiYABXJPFNCjoOcOiMcgcamNqtrYJWOBtzJVbrsDUvaNCiPuPKWRKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq'),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('GWQISPxqXfRsQhFJDCAVAOYWyxcJhFVpFkMUawfhLllPJQQrciPApZzKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio=')}) and v.StatsMiniTextPanelClass.TitleLabel.Text == gtZKSLKIUkfGcTPIIeDRykWkZeDlepbxzMMyncRnKRJzHGuZsjODAzhWHVEzcZPtvKkZYDMzWzFOKedrFYa({VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('hWHKqZGRUsLxNbjJfWxfbjUaDmLiGOMZUMQXwaFKdneOpmxlJXPpqJjKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('HULInQeATBCTNPmajPdMFOofUQXEygrCxVWFTkHCPRvGsuUrlBJIFFSKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('pkXwqmZiOcbrgZpiPDFPCXPEsHCFnqgfNXfqGTCkxhUdVouIRIalNpcKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKg==')}) then
        Memory = v.StatsMiniTextPanelClass.ValueLabel
    end
end

Memory:GetPropertyChangedSignal(gtZKSLKIUkfGcTPIIeDRykWkZeDlepbxzMMyncRnKRJzHGuZsjODAzhWHVEzcZPtvKkZYDMzWzFOKedrFYa({VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('zPeQCcQzkZWITuMqtZWOtGwltDYxodTsuAYszuRSaXbfUzUAovkZRjYKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq'),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('zfyYfritYeujkqULJNUrOXKlowDbZTkNpDPUpQjBTXtEjHgakpYygLyKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('SddGUqvVJZsIrjNHQZQVqvCUjCetHzFUPTXDqdGDFcolxBaTtaCsKxiKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq'),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('JZqbGcGdOmfnzLrakGoGQIqwkKDboxOLiSpGWsciCAPLiEDBujtwvtnKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio=')})):Connect(function()
    local Random = math.random(Settings.range1,Settings.range2)
    Random = Random * 1.23 
    Memory.Text = gtZKSLKIUkfGcTPIIeDRykWkZeDlepbxzMMyncRnKRJzHGuZsjODAzhWHVEzcZPtvKkZYDMzWzFOKedrFYa({}).. Random ..gtZKSLKIUkfGcTPIIeDRykWkZeDlepbxzMMyncRnKRJzHGuZsjODAzhWHVEzcZPtvKkZYDMzWzFOKedrFYa({VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('uxWoHlrAzGNjbHUhArPMDilawoRqZFlpaHGLHZgjLJToOWVPDZsGClRKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('BOLuwopTlmXqYtDciSRbMVRdKCdGZaHAqtgWZBCNBqVTwchsNARjIgEKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKio='),VRkUGVaHykjfBVnAIrErsTRfufyPDWVQSPTiJgLSYYVHrHfFNXbDXcPLyCCnEzq('khnGILmocbeawbytoADXdpCkuMtOxXbkTrCmxwajsXoajNsEwaPbNuXKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq')})
end)        